bl_info = {
    "name": "Scene From UE5",
    "author": "Generated by workflow assistant",
    "version": (0, 1, 0),
    "blender": (5, 0, 0),
    "location": "File > Import",
    "description": "Import a UE5 Level Sequence exported scene folder.",
    "category": "Import-Export",
    "support": "COMMUNITY",
    "wiki_url": "",
    "tracker_url": ""
}

import bpy

from .operators import SCENEUE5_OT_import

classes = [SCENEUE5_OT_import]


def register():
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
